// ─── Site Configuration ────────────────────────────────────────────────────
export const siteConfig = {
  name: 'Ilana Lewinsohn',
  handle: '@ilana.lewinsohn',
  tagline: 'Seja bem-vindo!',
  description:
    'Terapeuta corporal, facilitadora de Rodas de Mulheres e criadora do método MASSIXA — cuidado integrativo que une Yoga, Ayurveda, Xamanismo e a sabedoria da floresta.',
  about: [
    'Ilana Lewinsohn é a Guardiã da Descida do Instituto Canto da Floresta, em Arraial d\'Ajuda, Bahia. Bióloga, educadora e terapeuta corporal, ela transita há mais de duas décadas entre o estudo da natureza e os processos humanos de transformação, sempre a partir de uma certeza simples: somos natureza, sem separação.',
    'Ao longo de sua trajetória se aprofundou em Yoga, Ayurveda, Xamanismo e Alquimia, e é autora do método MASSIXA — Massagem Integrativa Xamânica —, além de facilitar Rodas de Mulheres desde 2012. Seu cuidado une toque, ervas, rituais e escuta, sempre construído a partir do que cada momento pede.',
    'Sua missão é apoiar o retorno de cada pessoa a si mesma, através da reconexão com a Terra, com o corpo e com os próprios ciclos — um convite para descer, enraizar e florescer.',
  ],
  heroImage: '/images/hero.jpg',
  aboutImage: '/images/bio.jpg',
  social: {
    instagram: 'https://instagram.com/ilana.lewinsohn',
    whatsapp: 'https://wa.me/557399855339',
  },
}

// ─── Services ──────────────────────────────────────────────────────────────
export type Service = {
  id: string
  slug: string
  title: string
  subtitle?: string
  description: string
  image: string
  ctaLabel: string
  ctaHref: string
  color?: string
}

export const services: Service[] = [
  {
    id: 'massixa-essencial',
    slug: 'massixa-essencial',
    title: 'MASSIXA Essencial',
    description: 'Toque em presença, escuta e elementos naturais para relaxamento profundo e reconexão com o corpo.',
    image: '/images/massixa-essencial.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/massixa-essencial',
  },
  {
    id: 'toque-da-jurema',
    slug: 'toque-da-jurema',
    title: 'MASSIXA Temática | Toque da Jurema',
    description: 'Toque vigoroso sobre cama de ervas, inspirado na força cabocla, para limpeza energética profunda.',
    image: '/images/toque-da-jurema.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/toque-da-jurema',
  },
  {
    id: 'madalena',
    slug: 'madalena',
    title: 'MASSIXA Temática | Madalena',
    description: 'Cacau cerimonial e toque de rosas vermelhas para abrir o coração e reconectar com a potência feminina.',
    image: '/images/madalena.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/madalena',
  },
  {
    id: 'anahata-terra',
    slug: 'anahata-terra',
    title: 'MASSIXA Temática | Anahata Terra',
    description: 'Argila, pedras quentes e ervas para enraizar o corpo e desacelerar a mente.',
    image: '/images/anahata-terra.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/anahata-terra',
  },
  {
    id: 'limpeza-da-fenix',
    slug: 'limpeza-da-fenix',
    title: 'MASSIXA Temática | Limpeza da Fênix',
    description: 'Ventosas e sangria terapêutica inspiradas no Taoísmo para liberar excessos e reequilibrar a energia.',
    image: '/images/limpeza-da-fenix.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/limpeza-da-fenix',
  },
  {
    id: 'imersao-colo-da-terra',
    slug: 'imersao-colo-da-terra',
    title: 'Imersão Colo da Terra',
    description: 'Imersão de cuidado para gestantes, respeitando cada fase da gravidez.',
    image: '/images/imersao-colo-da-terra.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/imersao-colo-da-terra',
  },
  {
    id: 'imersao-reconecta',
    slug: 'imersao-reconecta',
    title: 'Imersão Reconecta',
    description: 'Três horas dedicadas só a você — escuta, ritual, toque e ervas, no tempo que o momento pede.',
    image: '/images/imersao-reconecta.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/imersao-reconecta',
  },
  {
    id: 'vata-pitta-abhyanga',
    slug: 'vata-pitta-abhyanga',
    title: 'Vata-Pitta Abhyanga',
    description: 'Massagem ayurvédica com óleos aquecidos para nutrir os tecidos e acalmar a ansiedade.',
    image: '/images/vata-pitta-abhyanga.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/vata-pitta-abhyanga',
  },
  {
    id: 'kapha-abhyanga',
    slug: 'kapha-abhyanga',
    title: 'Kapha Abhyanga',
    description: 'Massagem ayurvédica vigorosa para ativar a circulação e despertar a vitalidade.',
    image: '/images/kapha-abhyanga.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/kapha-abhyanga',
  },
  {
    id: 'garshana',
    slug: 'garshana',
    title: 'Garshana',
    description: 'Esfoliação com óleo, ervas e sal para limpeza física e energética profunda.',
    image: '/images/garshana.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/garshana',
  },
  {
    id: 'shirodhara',
    slug: 'shirodhara',
    title: 'Shirodhara',
    description: 'Fluxo contínuo de óleo sobre o terceiro olho para acalmar profundamente corpo e mente.',
    image: '/images/shirodhara.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/shirodhara',
  },
  {
    id: 'escalda-pes-ritual',
    slug: 'escalda-pes-ritual',
    title: 'Escalda-Pés Ritual',
    description: 'Ritual com ervas e flores para acolher o corpo e repousar a mente, finalizado com chá.',
    image: '/images/escalda-pes-ritual.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/escalda-pes-ritual',
  },
  {
    id: 'cone-hindu',
    slug: 'cone-hindu',
    title: 'Cone Hindu (Hopi Candle)',
    description: 'Cuidado complementar tradicional para alívio de tensão, estresse e desconfortos nos ouvidos.',
    image: '/images/cone-hindu.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/cone-hindu',
  },
  {
    id: 'bussola-orientacao-xamanica',
    slug: 'bussola-orientacao-xamanica',
    title: 'Bússola: Orientação Integrativa Xamânica',
    description: 'Escuta e orientação xamânica para reencontrar o rumo, com roteiro personalizado por escrito.',
    image: '/images/bussola-orientacao-xamanica.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/bussola-orientacao-xamanica',
  },
  {
    id: 'acompanhamento-terapeutico',
    slug: 'acompanhamento-terapeutico',
    title: 'Acompanhamento Terapêutico Integrativo',
    description: 'Processo online continuado de escuta, orientação e práticas integrativas ao longo do tempo.',
    image: '/images/acompanhamento-terapeutico.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/acompanhamento-terapeutico',
  },
  {
    id: 'leitura-de-aura',
    slug: 'leitura-de-aura',
    title: 'Leitura de Aura',
    description: 'Avaliação energética à distância, com devolutiva em áudio no seu tempo.',
    image: '/images/leitura-de-aura.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/leitura-de-aura',
  },
  {
    id: 'rodas-celta-baianas',
    slug: 'rodas-celta-baianas',
    title: 'Rodas Celta-Baianas: Feminino Sagrado',
    description: 'Jornadas coletivas de fortalecimento feminino com ritual, cacau e partilha em círculo.',
    image: '/images/rodas-celta-baianas.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/rodas-celta-baianas',
  },
  {
    id: 'vivencias-imersoes-retiros',
    slug: 'vivencias-imersoes-retiros',
    title: 'Vivências, Imersões e Retiros',
    description: 'Experiências sob medida para grupos, comunidades e empresas, com práticas corporais e rituais.',
    image: '/images/vivencias-imersoes-retiros.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/vivencias-imersoes-retiros',
  },
  {
    id: 'mentoria-cuidado-autoral',
    slug: 'mentoria-cuidado-autoral',
    title: 'Mentoria Cuidado Autoral',
    description: 'Mentoria para terapeutas que querem fortalecer sua identidade profissional e linguagem própria de cuidado.',
    image: '/images/mentoria-cuidado-autoral.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/mentoria-cuidado-autoral',
  },
  {
    id: 'mentoria-vem-pra-roda-mulher',
    slug: 'mentoria-vem-pra-roda-mulher',
    title: 'Mentoria Vem Pra Roda, Mulher!',
    description: 'Mentoria para mulheres que desejam criar e conduzir Rodas de Mulheres.',
    image: '/images/mentoria-vem-pra-roda-mulher.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/mentoria-vem-pra-roda-mulher',
  },
  {
    id: 'biblioteca-viva',
    slug: 'biblioteca-viva',
    title: 'Biblioteca Viva',
    description: 'E-books e materiais de estudo sobre MASSIXA, Rodas Celta-Baianas e cozinha vegana ancestral.',
    image: '/images/biblioteca-viva.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/biblioteca-viva',
  },
  {
    id: 'botica-da-bruxa',
    slug: 'botica-da-bruxa',
    title: 'Botica da Bruxa',
    description: 'Preparados artesanais da Ervaria: pomadas, tinturas, óleos autorais e rapé.',
    image: '/images/botica-da-bruxa.jpg',
    ctaLabel: 'Saber mais',
    ctaHref: '/botica-da-bruxa',
  },
]
